service:
  name: product-service

frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  environment:
    SNS_ARN:
      Ref: SNSTopic
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'sqs:*'
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]
    - Effect: 'Allow'
      Action: 'sns:*'
      Resource:
        Ref: SNSTopic

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        ReceiveMessageWaitTimeSeconds: 20
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: catalogItemsNotificationTopic
    SNSSubscriptionSuccess:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: zhenyacher43@gmail.com
        Protocol: email
        FilterPolicy:
          isImportFailed: ['false']
        TopicArn:
          Ref: SNSTopic
    SNSSubscriptionFail:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: oigen43@icloud.com
        Protocol: email
        FilterPolicy:
          isImportFailed: ['true']
        TopicArn:
          Ref: SNSTopic
  Outputs:
    SQSQueueUrl:
      Value:
        Ref: SQSQueue
    SQSQueueArn:
      Value:
        Fn::GetAtt: [ SQSQueue, Arn ]

functions:
  getAllProducts:
    handler: index.getAllProducts
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: index.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
  createProduct:
    handler: index.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
  catalogBatchProcess:
    handler: index.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn