service:
  name: import-service

frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  environment:
    SQS_URL: ${cf:product-service-${self:provider.stage}.SQSQueueUrl}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::import-products/*"
    - Effect: 'Allow'
      Action: 'sqs:*'
      Resource:
        - '${cf:product-service-${self:provider.stage}.SQSQueueArn}'

functions:
  importProductsFile:
    handler: index.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: index.importFileParser
    events:
      - s3:
          bucket: import-products
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true